import type { CursorProfile } from "@/types/form";

export interface MockPolaroid {
  id: string;
  name: string;
  handle: string;
  avatar: string;
  image: string;
  date: string;
  profile: CursorProfile;
}

export const communityPolaroids: MockPolaroid[] = [
  {
    id: "1",
    name: "Sarah Chen",
    handle: "@sarahcodes",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    image: "https://picsum.photos/400/500?random=1",
    date: "2 days ago",
    profile: {
      handles: [{ handle: "@sarahcodes", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "agent",
      planTier: "pro",
      projectType: "Full-stack web app",
      extras: ["TypeScript", "React"],
      isMaxMode: true,
      cursorSince: "2024",
    },
  },
  {
    id: "2",
    name: "Marcus Johnson",
    handle: "@marcusdev",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=marcus",
    image: "https://picsum.photos/400/500?random=2",
    date: "5 days ago",
    profile: {
      handles: [{ handle: "@marcusdev", platform: "linkedin" }],
      primaryModel: "GPT-4o",
      secondaryModel: "Claude Sonnet 4.5",
      favoriteFeature: "tab",
      planTier: "ultra",
      projectType: "Mobile app",
      extras: ["React Native", "Node.js"],
      isMaxMode: false,
      cursorSince: "2023",
    },
  },
  {
    id: "3",
    name: "Emma Rodriguez",
    handle: "@emmarod",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    image: "https://picsum.photos/400/500?random=3",
    date: "1 week ago",
    profile: {
      handles: [{ handle: "@emmarod", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "browser",
      planTier: "pro-plus",
      projectType: "Data visualization",
      extras: ["Python", "D3.js"],
      isMaxMode: true,
      cursorSince: "2024",
    },
  },
  {
    id: "4",
    name: "Alex Kim",
    handle: "@alexkim",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    image: "https://picsum.photos/400/500?random=4",
    date: "3 days ago",
    profile: {
      handles: [{ handle: "@alexkim", platform: "linkedin" }],
      primaryModel: "GPT-4o",
      secondaryModel: "Claude Sonnet 4.5",
      favoriteFeature: "voice",
      planTier: "pro",
      projectType: "API backend",
      extras: ["Go", "PostgreSQL"],
      isMaxMode: false,
      cursorSince: "recently",
    },
  },
  {
    id: "5",
    name: "Jordan Taylor",
    handle: "@jordant",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan",
    image: "https://picsum.photos/400/500?random=5",
    date: "6 days ago",
    profile: {
      handles: [{ handle: "@jordant", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "agent",
      planTier: "ultra",
      projectType: "E-commerce platform",
      extras: ["Next.js", "Stripe"],
      isMaxMode: true,
      cursorSince: "2023",
    },
  },
  {
    id: "6",
    name: "Riley Patel",
    handle: "@rileyp",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=riley",
    image: "https://picsum.photos/400/500?random=6",
    date: "4 days ago",
    profile: {
      handles: [{ handle: "@rileyp", platform: "linkedin" }],
      primaryModel: "GPT-4o",
      secondaryModel: "Claude Sonnet 4.5",
      favoriteFeature: "tab",
      planTier: "pro",
      projectType: "Design system",
      extras: ["Figma", "Storybook"],
      isMaxMode: false,
      cursorSince: "2024",
    },
  },
  {
    id: "7",
    name: "Casey Wong",
    handle: "@caseyw",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=casey",
    image: "https://picsum.photos/400/500?random=7",
    date: "1 week ago",
    profile: {
      handles: [{ handle: "@caseyw", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "browser",
      planTier: "pro-plus",
      projectType: "AI chatbot",
      extras: ["OpenAI", "LangChain"],
      isMaxMode: true,
      cursorSince: "2024",
    },
  },
  {
    id: "8",
    name: "Morgan Lee",
    handle: "@morganl",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=morgan",
    image: "https://picsum.photos/400/500?random=8",
    date: "2 days ago",
    profile: {
      handles: [{ handle: "@morganl", platform: "linkedin" }],
      primaryModel: "GPT-4o",
      secondaryModel: "Claude Sonnet 4.5",
      favoriteFeature: "rules",
      planTier: "ultra",
      projectType: "DevOps automation",
      extras: ["Docker", "Kubernetes"],
      isMaxMode: false,
      cursorSince: "2023",
    },
  },
];

export const userPolaroids: MockPolaroid[] = [
  {
    id: "user-1",
    name: "You",
    handle: "@you",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
    image: "https://picsum.photos/400/500?random=10",
    date: "1 week ago",
    profile: {
      handles: [{ handle: "@you", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "agent",
      planTier: "pro",
      projectType: "Portfolio site",
      extras: ["React", "TypeScript"],
      isMaxMode: true,
      cursorSince: "2024",
    },
  },
  {
    id: "user-2",
    name: "You",
    handle: "@you",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
    image: "https://picsum.photos/400/500?random=11",
    date: "2 weeks ago",
    profile: {
      handles: [{ handle: "@you", platform: "linkedin" }],
      primaryModel: "GPT-4o",
      secondaryModel: "Claude Sonnet 4.5",
      favoriteFeature: "tab",
      planTier: "pro-plus",
      projectType: "Blog platform",
      extras: ["Next.js", "MDX"],
      isMaxMode: false,
      cursorSince: "2024",
    },
  },
  {
    id: "user-3",
    name: "You",
    handle: "@you",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
    image: "https://picsum.photos/400/500?random=12",
    date: "3 weeks ago",
    profile: {
      handles: [{ handle: "@you", platform: "x" }],
      primaryModel: "Claude Sonnet 4.5",
      secondaryModel: "GPT-4o",
      favoriteFeature: "browser",
      planTier: "ultra",
      projectType: "Dashboard app",
      extras: ["Vue", "D3.js"],
      isMaxMode: true,
      cursorSince: "2023",
    },
  },
];


